local dlg = require ('gui.dialogs')

msg6=("Among the gear is a ledger with building plans for all dwarven workshops, better make use of it.")
dlg.showMessage("A chance encounter", msg6, COLOR_WHITE, nil)
msg5=("You decide to give the dwarves a proper burial; least they haunt you for using their equipment.")
dlg.showMessage("A chance encounter", msg5, COLOR_WHITE, nil)
msg4=("The wagon now yours, you claim your price. The dead have no need for it; you on the other hand...")
dlg.showMessage("A chance encounter", msg4, COLOR_WHITE, nil)
msg3=("The goods in the wagon seem intact; curiously enough 7 coffins are among the assorted items.")
dlg.showMessage("A chance encounter", msg3, COLOR_WHITE, nil)
msg2=("With no attacker in sight and no trail to follow, you carefully decide to have a closer look.")
dlg.showMessage("A chance encounter", msg2, COLOR_WHITE, nil)
msg1=("You come upon a group of dead dwarves, horribly mauled, laying next to their abandoned wagon.")
dlg.showMessage("A chance encounter", msg1, COLOR_WHITE, nil)